server:
  port: 8088
  servlet:
    context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?characterEncoding=utf-8
  mvc:
    view:
      prefix: /jsp
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      force-request: true
      force-response: true
  redis:
    cluster:
      nodes: 192.168.159.20:7000,192.168.159.20:7001,192.168.159.20:7003,192.168.159.20:7004,192.168.159.20:7005,192.168.159.20:7006,192.168.159.20:7002
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: com/baizhi/mapper/*Mapper.xml

logging:
  level:
    com.baizhi.dao: debug
    root: error
